### ISSUE TITLE
Fehler: uncaught exception: The value of "offset" is out of range. It must be >= 0 and <= 0. Received 4

### ISSUE THREAD

**Issue by Tuphal** [UncleSamSwiss/ioBroker.luxtronik2#20]
Ich bekomme bei jeder Aktualisierung folgenden Fehler:
```
> 2020-12-26 00:08:58.455  - error: luxtronik2.0 (1791) uncaught exception: The value of "offset" is out of range. It must be >= 0 and <= 0. Received 4
> --
> 2020-12-26 00:08:58.456  - error:  luxtronik2.0 (1791) RangeError [ERR_OUT_OF_RANGE]: The value of  "offset" is out of range. It must be >= 0 and <= 0. Received 4
> at boundsError (internal/buffer.js:82:9)
> at Buffer.readInt32BE (internal/buffer.js:478:5)
> at Luxtronik. (/opt/iobroker/node_modules/luxtronik2/luxtronik.js:406:37)
> at Socket.emit (events.js:314:20)
> at addChunk (_stream_readable.js:297:12)
> at readableAddChunk (_stream_readable.js:272:9)
> at Socket.Readable.push (_stream_readable.js:213:10)
> at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
> 2020-12-26 00:08:58.464  - info: luxtronik2.0 (1791) terminating
> 2020-12-26 00:08:58.465  - info: luxtronik2.0 (1791) Terminated (NO_ERROR): Without reason
> 2020-12-26 00:08:58.496  - error: luxtronik2.0 (1791) uncaught exception: The value of "offset" is out of range. It must be >= 0 and <= 0. Received 4
> 2020-12-26 00:08:58.496  - error:  luxtronik2.0 (1791) RangeError [ERR_OUT_OF_RANGE]: The value of  "offset" is out of range. It must be >= 0 and <= 0. Received 4
> at boundsError (internal/buffer.js:82:9)
> at Buffer.readInt32BE (internal/buffer.js:478:5)
> at Luxtronik. (/opt/iobroker/node_modules/luxtronik2/luxtronik.js:390:37)
> at Socket.emit (events.js:314:20)
> at addChunk (_stream_readable.js:297:12)
> at readableAddChunk (_stream_readable.js:272:9)
> at Socket.Readable.push (_stream_readable.js:213:10)
> at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
> 2020-12-26 00:08:58.535  - error: luxtronik2.0 (1791) uncaught exception: The value of "offset" is out of range. It must be >= 0 and <= 0. Received 4
> 2020-12-26 00:08:58.536  - error:  luxtronik2.0 (1791) RangeError [ERR_OUT_OF_RANGE]: The value of  "offset" is out of range. It must be >= 0 and <= 0. Received 4
> at boundsError (internal/buffer.js:82:9)
> at Buffer.readInt32BE (internal/buffer.js:478:5)
> at Luxtronik. (/opt/iobroker/node_modules/luxtronik2/luxtronik.js:406:37)
> at Socket.emit (events.js:314:20)
> at addChunk (_stream_readable.js:297:12)
> at readableAddChunk (_stream_readable.js:272:9)
> at Socket.Readable.push (_stream_readable.js:213:10)
> at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

Wärmepumpe: Alha-Innotec
Softwarestand: V3.85.1 (r5783)

![grafik](https://user-images.githubusercontent.com/42291781/103142981-a9920c80-470d-11eb-819b-825217b60aa9.png)

**Edit: Log Output formatiert**

**Comment by UncleSamSwiss** [comment]
Das ist leider ein [bekanntes Problem](https://github.com/coolchip/luxtronik2/issues/11) der darunter liegenden Library.

Es gibt aktuell einen kleinen "Hack" in meinem Adapter (den ich bei mir auch anwede):
Du musst manuell in den Einstellungen zur Adapter Instanz die Variable `useLuxProxy: true` setzen.
Der einfachste Weg ist:
1. in der Objekt-Ansicht in Admin den Experten-Modus einschalten
2. bei system.adapter.luxtronik2.0 ganz rechts auf den Bleistift klicken
3. auf den Tab "Native" wechseln
4. dort auf das "+" Symbol klicken
5. im Dialog den Namen "useLuxProxy" eingeben
6. im neuen Feld den Wert "true" eingeben
7. "Speichern" klicken
8. den Experten-Modus wieder ausschalten

**Comment by Tuphal** [comment]
funktioniert perfekt. 
Danke!

**Comment by robseh** [comment]
Moin! Ich kann leider den Tab "Native" nicht finden. Ist der bei einem Update irgendwo verloren gegangen? Oder bin ich falsch davor? 
Kann man das sonst direkt in die Objektdaten irgendwo eintragen?
![Bildschirmfoto 2021-09-05 um 22 12 41](https://user-images.githubusercontent.com/90156251/132140328-04d0fdfc-2271-4145-92cb-40361b1a1f6f.png)
Ich danke Euch für die Unterstützung!
