### ISSUE TITLE
Adapter crashing: Cannot read properties of null (reading 'end')

### ISSUE THREAD

**Issue by stfh1** [UncleSamSwiss/ioBroker.luxtronik2#247]
**Describe the bug**  
Adapter terminating with error "Cannot read properties of null (reading 'end')"

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/107648523/174154259-76736182-c467-441c-84cd-2738332b53bd.png)

![image](https://user-images.githubusercontent.com/107648523/174154823-47ed502b-70eb-44c9-ad77-71bcfb241ac1.png)

<html>
<body>

host.homebridge | 2022-06-16 22:04:49.559 | warn | Do not restart adapter system.adapter.luxtronik2.0 because restart loop detected
-- | -- | -- | --
host.homebridge | 2022-06-16 22:04:49.559 | info | Restart adapter system.adapter.luxtronik2.0 because enabled
host.homebridge | 2022-06-16 22:04:49.557 | error | instance system.adapter.luxtronik2.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
luxtronik2.0 | 2022-06-16 22:04:48.965 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
luxtronik2.0 | 2022-06-16 22:04:48.963 | info | terminating
luxtronik2.0 | 2022-06-16 22:04:48.955 | error | Cannot read properties of null (reading 'end')
luxtronik2.0 | 2022-06-16 22:04:48.953 | error | TypeError: Cannot read properties of null (reading 'end') at Luxtronik._nextJob (/opt/iobroker/node_modules/luxtronik2/luxtronik.js:444:21) at processTicksAndRejections (node:internal/process/task_queues:78:11)
luxtronik2.0 | 2022-06-16 22:04:48.951 | error | uncaught exception: Cannot read properties of null (reading 'end')
luxtronik2.0 | 2022-06-16 22:04:48.945 | error | Cannot read properties of null (reading 'end')
luxtronik2.0 | 2022-06-16 22:04:48.943 | error | TypeError: Cannot read properties of null (reading 'end') at Luxtronik._nextJob (/opt/iobroker/node_modules/luxtronik2/luxtronik.js:444:21) at processTicksAndRejections (node:internal/process/task_queues:78:11)
luxtronik2.0 | 2022-06-16 22:04:48.941 | error | uncaught exception: Cannot read properties of null (reading 'end')
luxtronik2.0 | 2022-06-16 22:04:48.932 | error | Luxtronik read error, will retry later: Error: Missing element at luxtronik response to 3005

</body>
</html>

**Versions:**  
 - Adapter version: 0.4.2
 - JS-Controller version: 5.7.0
 - Novelan/Luxtronik Firmware: 3.87

**Comment by R3dRuM** [comment]
same here:
> 2022-09-14 16:09:54.981 - error: host.iobroker Caught by controller[0]: TypeError: Cannot read property 'end' of null
--
2022-09-14 16:09:54.982 - error: host.iobroker Caught by controller[0]: at Luxtronik._nextJob (/opt/iobroker/node_modules/luxtronik2/luxtronik.js:431:21)
2022-09-14 16:09:54.983 - error: host.iobroker Caught by controller[0]: at processTicksAndRejections (internal/process/task_queues.js:77:11)
2022-09-14 16:09:54.983 - error: host.iobroker Caught by controller[1]: SentryError: HTTP Error (403)
2022-09-14 16:09:54.983 - error: host.iobroker Caught by controller[1]: at new SentryError (/opt/iobroker/node_modules/@iobroker/plugin-sentry/node_modules/@sentry/src/error.ts:9:5)
2022-09-14 16:09:54.983 - error: host.iobroker Caught by controller[1]: at ClientRequest. (/opt/iobroker/node_modules/@iobroker/plugin-sentry/node_modules/@sentry/src/transports/base/index.ts:254:22)
2022-09-14 16:09:54.984 - error: host.iobroker Caught by controller[1]: at Object.onceWrapper (events.js:520:26)
2022-09-14 16:09:54.984 - error: host.iobroker Caught by controller[1]: at ClientRequest.emit (events.js:400:28)
2022-09-14 16:09:54.984 - error: host.iobroker Caught by controller[1]: at ClientRequest.emit (domain.js:475:12)
2022-09-14 16:09:54.984 - error: host.iobroker Caught by controller[1]: at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
2022-09-14 16:09:54.984 - error: host.iobroker Caught by controller[1]: at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
2022-09-14 16:09:54.985 - error: host.iobroker Caught by controller[1]: at TLSSocket.socketOnData (_http_client.js:515:22)
2022-09-14 16:09:54.985 - error: host.iobroker Caught by controller[1]: at TLSSocket.emit (events.js:400:28)
2022-09-14 16:09:54.985 - error: host.iobroker Caught by controller[1]: at TLSSocket.emit (domain.js:475:12)
2022-09-14 16:09:54.985 - error: host.iobroker instance system.adapter.luxtronik2.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

Versions:

- Adapter version: 0.4.2
- JS-Controller version: 4.0.23
- Luxtronik Firmware:  V3.85.7 (r6978)
